USE project;
DROP TABLE IF EXISTS Tracks;

create table Tracks (
track_id INT NOT NULL PRIMARY KEY, 
album_comments INT,
album_date_created INT,
album_date_released INT,
album_engineer VARCHAR (255),
album_favorites INT,
album_id INT,
album_listens INT,
album_producer VARCHAR (1000),	
album_tags VARCHAR (255),
album_title VARCHAR (255),				
album_tracks INT,
album_type VARCHAR (256),
artist_active_year_begin INT,
artist_active_year_end INT,
artist_associated_labels VARCHAR (1000),
artist_comments INT,
artist_date_created INT,
artist_favorites INT,
artist_id INT,
artist_latitude INT,
artist_location VARCHAR (1000),
artist_longitude INT,
artist_members VARCHAR (1000),
artist_name VARCHAR (1000),
artist_related_projects VARCHAR (500),
artist_tags VARCHAR (500),
artist_website VARCHAR (500),
artist_wikipedia_page VARCHAR (1000),
set_split VARCHAR (255),
set_subset VARCHAR (255),
track_bit_rate INT,
track_comments INT,
track_composer VARCHAR (255),
track_date_created INT,
track_date_recorded INT,
track_duration	INT,
track_favorites INT,
track_genre_top VARCHAR (500),
track_genres VARCHAR (255),
track_genres_all VARCHAR (255),
track_interest INT,
track_language_code VARCHAR (255),
track_license VARCHAR(500),
track_listens INT,
track_lyricist VARCHAR(500),
track_number INT, 
track_publisher VARCHAR(1000),
track_tags VARCHAR (500),
track_title VARCHAR (500));

load data local infile '/home/hduser/workspace/FMA_Project/tracks_project.csv' into table Tracks fields terminated by ',';

